# Generated by Django 2.2.6 on 2019-10-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
