# Generated by Django 2.2.6 on 2019-10-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_name', models.CharField(max_length=200)),
                ('stars', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('pic', models.FileField(blank=True, null=True, upload_to='')),
                ('facilities', models.CharField(max_length=200)),
                ('lattitude', models.CharField(max_length=200)),
                ('contact', models.BigIntegerField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
