# Generated by Django 2.2.6 on 2019-10-31 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20191030_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('hotels_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.hotel')),
            ],
        ),
    ]
